graph_generator:
  ros__parameters:

    loop_rate: 0.1
    publish_voronoi_map_image: False
    map_inflation: 0.1
    segment_length: 5.0
    opt_crossings: 0.5
    opt_end_segments: 2.0
    graph_cache_path: $(var path)/cfg/graph/$(var cfg)/cache/
    # custom_graph_path: $(var custom_graph_path) 