/$(var namespace)/best_vertices_node:
  ros__parameters:
    ns: /$(var namespace)
    n_robots: $(var n_robots)
    human_pos: $(var human_pos)
    radius: $(var radius) 
    env: $(var env) 
    update_rate_info: $(var update_rate_info) 
    map_topic: /robot1/map
    voronoi_map_topic: /$(var namespace)/voronoi_map
    segment_topic: /$(var namespace)/segments
 

