/$(var namespace)/best_vertices_node:
  ros__parameters:
    n_robots: 6
    human_pos: [0.0,0.0]
    radius: 20.0
    env: $(var env) 
    update_rate_info: 1.0
    map_topic: /robot1/map   
    voronoi_map_topic: voronoi_map
    segment_topic: segments
 

